const tradingHistory = [
    {
      "Action": "Deposit",
      "Time": "2020-02-28 23:38:42",
      "ISIN": "",
      "Ticker": "",
      "Name": "",
      "No. of shares": "",
      "Price / share": "",
      "Currency (Price / share)": "",
      "Exchange rate": "",
      "Result (EUR)": "",
      "Total (EUR)": "1.00",
      "Charge amount (EUR)": "1.00",
      "Stamp duty reserve tax (EUR)": "",
      "Notes": "\"Transaction ID: \"",
      "ID": "",
      "Currency conversion fee (EUR)": ""
    },
    {
      "Action": "Market buy",
      "Time": "2020-03-04 08:00:34",
      "ISIN": "IE00B4ND3602",
      "Ticker": "SGLN",
      "Name": "\"iShares Physical Gold\"",
      "No. of shares": "0.0300000000",
      "Price / share": "2502.00",
      "Currency (Price / share)": "GBX",
      "Exchange rate": "87.24299",
      "Result (EUR)": "",
      "Total (EUR)": "0.86",
      "Charge amount (EUR)": "",
      "Stamp duty reserve tax (EUR)": "",
      "Notes": "",
      "ID": "",
      "Currency conversion fee (EUR)": ""
    },
    {
      "Action": "Deposit",
      "Time": "2020-04-14 16:36:29",
      "ISIN": "",
      "Ticker": "",
      "Name": "",
      "No. of shares": "",
      "Price / share": "",
      "Currency (Price / share)": "",
      "Exchange rate": "",
      "Result (EUR)": "",
      "Total (EUR)": "10.00",
      "Charge amount (EUR)": "10.00",
      "Stamp duty reserve tax (EUR)": "",
      "Notes": "\"Transaction ID: \"",
      "ID": "",
      "Currency conversion fee (EUR)": ""
    },
    {
      "Action": "Market buy",
      "Time": "2020-04-15 07:01:00",
      "ISIN": "IE00B4ND3602",
      "Ticker": "SGLN",
      "Name": "\"iShares Physical Gold\"",
      "No. of shares": "0.2800000000",
      "Price / share": "2669.00",
      "Currency (Price / share)": "GBX",
      "Exchange rate": "87.16699",
      "Result (EUR)": "",
      "Total (EUR)": "8.57",
      "Charge amount (EUR)": "",
      "Stamp duty reserve tax (EUR)": "",
      "Notes": "",
      "ID": "",
      "Currency conversion fee (EUR)": ""
    },
    {
      "Action": "Market sell",
      "Time": "2020-06-04 07:00:44",
      "ISIN": "IE00B4ND3602",
      "Ticker": "SGLN",
      "Name": "\"iShares Physical Gold\"",
      "No. of shares": "0.3100000000",
      "Price / share": "2652.00",
      "Currency (Price / share)": "GBX",
      "Exchange rate": "89.46180",
      "Result (EUR)": "-0.24",
      "Total (EUR)": "9.19",
      "Charge amount (EUR)": "",
      "Stamp duty reserve tax (EUR)": "",
      "Notes": "",
      "ID": "",
      "Currency conversion fee (EUR)": ""
    },
    {
      "Action": "Market buy",
      "Time": "2020-06-11 10:36:01",
      "ISIN": "GB00BMBVGQ36",
      "Ticker": "HBR",
      "Name": "\"Harbour Energy \"",
      "No. of shares": "7.5000000000",
      "Price / share": "43.60",
      "Currency (Price / share)": "GBX",
      "Exchange rate": "89.70695",
      "Result (EUR)": "",
      "Total (EUR)": "3.67",
      "Charge amount (EUR)": "",
      "Stamp duty reserve tax (EUR)": "0.02",
      "Notes": "",
      "ID": "",
      "Currency conversion fee (EUR)": ""
    },
    {
      "Action": "Market sell",
      "Time": "2020-06-11 10:38:32",
      "ISIN": "GB00BMBVGQ36",
      "Ticker": "HBR",
      "Name": "\"Harbour Energy \"",
      "No. of shares": "7.5000000000",
      "Price / share": "43.47",
      "Currency (Price / share)": "GBX",
      "Exchange rate": "89.73692",
      "Result (EUR)": "-0.02",
      "Total (EUR)": "3.63",
      "Charge amount (EUR)": "",
      "Stamp duty reserve tax (EUR)": "",
      "Notes": "",
      "ID": "",
      "Currency conversion fee (EUR)": ""
    },
    {
      "Action": "Market buy",
      "Time": "2020-06-11 13:32:58",
      "ISIN": "US88160R1014",
      "Ticker": "TSLA",
      "Name": "\"Tesla\"",
      "No. of shares": "0.0060000000",
      "Price / share": "989.62",
      "Currency (Price / share)": "USD",
      "Exchange rate": "1.13653",
      "Result (EUR)": "",
      "Total (EUR)": "5.22",
      "Charge amount (EUR)": "",
      "Stamp duty reserve tax (EUR)": "",
      "Notes": "",
      "ID": "",
      "Currency conversion fee (EUR)": ""
    },
    {
      "Action": "Deposit",
      "Time": "2020-08-29 08:13:08",
      "ISIN": "",
      "Ticker": "",
      "Name": "",
      "No. of shares": "",
      "Price / share": "",
      "Currency (Price / share)": "",
      "Exchange rate": "",
      "Result (EUR)": "",
      "Total (EUR)": "5.87",
      "Charge amount (EUR)": "5.87",
      "Stamp duty reserve tax (EUR)": "",
      "Notes": "\"TSLA split\"",
      "ID": "",
      "Currency conversion fee (EUR)": ""
    },
    {
      "Action": "Market buy",
      "Time": "2020-10-06 13:31:30",
      "ISIN": "US29786A1060",
      "Ticker": "ETSY",
      "Name": "\"Etsy\"",
      "No. of shares": "0.1350000000",
      "Price / share": "137.22",
      "Currency (Price / share)": "USD",
      "Exchange rate": "1.17966",
      "Result (EUR)": "",
      "Total (EUR)": "15.70",
      "Charge amount (EUR)": "",
      "Stamp duty reserve tax (EUR)": "",
      "Notes": "",
      "ID": "",
      "Currency conversion fee (EUR)": ""
    },
    {
      "Action": "Market sell",
      "Time": "2020-10-19 13:30:48",
      "ISIN": "US29786A1060",
      "Ticker": "ETSY",
      "Name": "\"Etsy\"",
      "No. of shares": "0.1350000000",
      "Price / share": "148.76",
      "Currency (Price / share)": "USD",
      "Exchange rate": "1.17823",
      "Result (EUR)": "1.34",
      "Total (EUR)": "17.04",
      "Charge amount (EUR)": "",
      "Stamp duty reserve tax (EUR)": "",
      "Notes": "",
      "ID": "",
      "Currency conversion fee (EUR)": ""
    },
    {
      "Action": "Market buy",
      "Time": "2020-10-27 08:03:04",
      "ISIN": "DE0007164600",
      "Ticker": "SAP",
      "Name": "\"SAP SE\"",
      "No. of shares": "0.1650000000",
      "Price / share": "99.85",
      "Currency (Price / share)": "EUR",
      "Exchange rate": "1.00000",
      "Result (EUR)": "",
      "Total (EUR)": "16.48",
      "Charge amount (EUR)": "",
      "Stamp duty reserve tax (EUR)": "",
      "Notes": "",
      "ID": "",
      "Currency conversion fee (EUR)": ""
    },
    {
      "Action": "Deposit",
      "Time": "2021-01-27 18:26:01",
      "ISIN": "",
      "Ticker": "",
      "Name": "",
      "No. of shares": "",
      "Price / share": "",
      "Currency (Price / share)": "",
      "Exchange rate": "",
      "Result (EUR)": "",
      "Total (EUR)": "50.00",
      "Charge amount (EUR)": "50.00",
      "Notes": "\"Transaction ID: \"",
      "ID": "",
      "Currency conversion fee (EUR)": "",
      "Stamp duty reserve tax (EUR)": ""
    },
    {
      "Action": "Market buy",
      "Time": "2021-01-27 18:27:35",
      "ISIN": "US00165C1045",
      "Ticker": "AMC",
      "Name": "\"AMC Entertainment Holdings\"",
      "No. of shares": "3.6000000000",
      "Price / share": "16.29",
      "Currency (Price / share)": "USD",
      "Exchange rate": "1.21118",
      "Result (EUR)": "",
      "Total (EUR)": "48.42",
      "Charge amount (EUR)": "",
      "Notes": "",
      "ID": "",
      "Currency conversion fee (EUR)": "",
      "Stamp duty reserve tax (EUR)": ""
    },
    {
      "Action": "Deposit",
      "Time": "2021-01-27 20:14:33",
      "ISIN": "",
      "Ticker": "",
      "Name": "",
      "No. of shares": "",
      "Price / share": "",
      "Currency (Price / share)": "",
      "Exchange rate": "",
      "Result (EUR)": "",
      "Total (EUR)": "50.00",
      "Charge amount (EUR)": "50.00",
      "Notes": "\"Transaction ID: \"",
      "ID": "",
      "Currency conversion fee (EUR)": "",
      "Stamp duty reserve tax (EUR)": ""
    },
    {
      "Action": "Market buy",
      "Time": "2021-01-27 20:23:07",
      "ISIN": "US6549022043",
      "Ticker": "NOK",
      "Name": "\"Nokia ADR\"",
      "No. of shares": "8.6000000000",
      "Price / share": "7.12",
      "Currency (Price / share)": "USD",
      "Exchange rate": "1.21005",
      "Result (EUR)": "",
      "Total (EUR)": "50.60",
      "Charge amount (EUR)": "",
      "Notes": "",
      "ID": "",
      "Currency conversion fee (EUR)": "",
      "Stamp duty reserve tax (EUR)": ""
    },
    {
      "Action": "Market sell",
      "Time": "2021-01-28 08:02:29",
      "ISIN": "DE0007164600",
      "Ticker": "SAP",
      "Name": "\"SAP SE\"",
      "No. of shares": "0.1650000000",
      "Price / share": "108.20",
      "Currency (Price / share)": "EUR",
      "Exchange rate": "1.00000",
      "Result (EUR)": "1.37",
      "Total (EUR)": "17.85",
      "Charge amount (EUR)": "",
      "Notes": "",
      "ID": "",
      "Currency conversion fee (EUR)": "",
      "Stamp duty reserve tax (EUR)": ""
    },
    {
      "Action": "Market sell",
      "Time": "2021-01-28 14:37:17",
      "ISIN": "US6549022043",
      "Ticker": "NOK",
      "Name": "\"Nokia ADR\"",
      "No. of shares": "8.6000000000",
      "Price / share": "5.48",
      "Currency (Price / share)": "USD",
      "Exchange rate": "1.21351",
      "Result (EUR)": "-11.76",
      "Total (EUR)": "38.84",
      "Charge amount (EUR)": "",
      "Notes": "",
      "ID": "",
      "Currency conversion fee (EUR)": "",
      "Stamp duty reserve tax (EUR)": ""
    },
    {
      "Action": "Market sell",
      "Time": "2021-01-28 15:12:31",
      "ISIN": "US00165C1045",
      "Ticker": "AMC",
      "Name": "\"AMC Entertainment Holdings\"",
      "No. of shares": "3.6000000000",
      "Price / share": "13.02",
      "Currency (Price / share)": "USD",
      "Exchange rate": "1.21415",
      "Result (EUR)": "-9.82",
      "Total (EUR)": "38.60",
      "Charge amount (EUR)": "",
      "Notes": "",
      "ID": "",
      "Currency conversion fee (EUR)": "",
      "Stamp duty reserve tax (EUR)": ""
    },
    {
      "Action": "Market buy",
      "Time": "2021-01-28 15:16:51",
      "ISIN": "US5916971071",
      "Ticker": "MILE",
      "Name": "\"MetroMile\"",
      "No. of shares": "4.0000000000",
      "Price / share": "14.27",
      "Currency (Price / share)": "USD",
      "Exchange rate": "1.21373",
      "Result (EUR)": "",
      "Total (EUR)": "47.03",
      "Charge amount (EUR)": "",
      "Notes": "",
      "ID": "",
      "Currency conversion fee (EUR)": "",
      "Stamp duty reserve tax (EUR)": ""
    },
    {
      "Action": "Market buy",
      "Time": "2021-01-29 15:24:48",
      "ISIN": "US6549022043",
      "Ticker": "NOK",
      "Name": "\"Nokia ADR\"",
      "No. of shares": "4.5000000000",
      "Price / share": "5.00",
      "Currency (Price / share)": "USD",
      "Exchange rate": "1.21407",
      "Result (EUR)": "",
      "Total (EUR)": "18.53",
      "Charge amount (EUR)": "",
      "Notes": "",
      "ID": "",
      "Currency conversion fee (EUR)": "",
      "Stamp duty reserve tax (EUR)": ""
    },
    {
      "Action": "Market buy",
      "Time": "2021-01-29 17:20:31",
      "ISIN": "US35953D1046",
      "Ticker": "FUBO",
      "Name": "\"fuboTV\"",
      "No. of shares": "0.7200000000",
      "Price / share": "43.04",
      "Currency (Price / share)": "USD",
      "Exchange rate": "1.21352",
      "Result (EUR)": "",
      "Total (EUR)": "25.54",
      "Charge amount (EUR)": "",
      "Notes": "",
      "ID": "",
      "Currency conversion fee (EUR)": "",
      "Stamp duty reserve tax (EUR)": ""
    },
    {
      "Action": "Market buy",
      "Time": "2021-02-01 13:57:30",
      "ISIN": "US1251051066",
      "Ticker": "OTGLY",
      "Name": "\"CD Projekt\"",
      "No. of shares": "0.3600000000",
      "Price / share": "20.60",
      "Currency (Price / share)": "USD",
      "Exchange rate": "1.20883",
      "Result (EUR)": "",
      "Total (EUR)": "6.13",
      "Charge amount (EUR)": "",
      "Notes": "",
      "ID": "",
      "Currency conversion fee (EUR)": "",
      "Stamp duty reserve tax (EUR)": ""
    },
    {
      "Action": "Deposit",
      "Time": "2021-02-01 14:53:59",
      "ISIN": "",
      "Ticker": "",
      "Name": "",
      "No. of shares": "",
      "Price / share": "",
      "Currency (Price / share)": "",
      "Exchange rate": "",
      "Result (EUR)": "",
      "Total (EUR)": "25.00",
      "Charge amount (EUR)": "25.00",
      "Notes": "\"Transaction ID: \"",
      "ID": "",
      "Currency conversion fee (EUR)": "",
      "Stamp duty reserve tax (EUR)": ""
    },
    {
      "Action": "Market buy",
      "Time": "2021-02-01 14:54:15",
      "ISIN": "US92532F1003",
      "Ticker": "VRTX",
      "Name": "\"Vertex Pharmaceuticals\"",
      "No. of shares": "0.1150000000",
      "Price / share": "226.61",
      "Currency (Price / share)": "USD",
      "Exchange rate": "1.20872",
      "Result (EUR)": "",
      "Total (EUR)": "21.56",
      "Charge amount (EUR)": "",
      "Notes": "",
      "ID": "",
      "Currency conversion fee (EUR)": "",
      "Stamp duty reserve tax (EUR)": ""
    },
    {
      "Action": "Market sell",
      "Time": "2021-02-02 14:30:34",
      "ISIN": "US6549022043",
      "Ticker": "NOK",
      "Name": "\"Nokia ADR\"",
      "No. of shares": "4.5000000000",
      "Price / share": "4.73",
      "Currency (Price / share)": "USD",
      "Exchange rate": "1.20429",
      "Result (EUR)": "-0.86",
      "Total (EUR)": "17.67",
      "Charge amount (EUR)": "",
      "Notes": "",
      "ID": "",
      "Currency conversion fee (EUR)": "",
      "Stamp duty reserve tax (EUR)": ""
    },
    {
      "Action": "Market sell",
      "Time": "2021-02-09 13:13:15",
      "ISIN": "US1251051066",
      "Ticker": "OTGLY",
      "Name": "\"CD Projekt\"",
      "No. of shares": "0.3600000000",
      "Price / share": "18.00",
      "Currency (Price / share)": "USD",
      "Exchange rate": "1.21057",
      "Result (EUR)": "-0.78",
      "Total (EUR)": "5.35",
      "Charge amount (EUR)": "",
      "Notes": "",
      "ID": "",
      "Currency conversion fee (EUR)": "",
      "Stamp duty reserve tax (EUR)": ""
    },
    {
      "Action": "Market buy",
      "Time": "2021-02-09 14:30:23",
      "ISIN": "US72352L1061",
      "Ticker": "PINS",
      "Name": "\"Pinterest\"",
      "No. of shares": "0.3500000000",
      "Price / share": "79.50",
      "Currency (Price / share)": "USD",
      "Exchange rate": "1.20950",
      "Result (EUR)": "",
      "Total (EUR)": "23.01",
      "Charge amount (EUR)": "",
      "Notes": "",
      "ID": "",
      "Currency conversion fee (EUR)": "",
      "Stamp duty reserve tax (EUR)": ""
    },
    {
      "Action": "Market sell",
      "Time": "2021-06-08 16:52:21",
      "ISIN": "US35953D1046",
      "Ticker": "FUBO",
      "Name": "\"fuboTV\"",
      "No. of shares": "0.7200000000",
      "Price / share": "30.20",
      "Currency (Price / share)": "USD",
      "Exchange rate": "1.21819",
      "Result (EUR)": "-7.69",
      "Total (EUR)": "17.82",
      "Charge amount (EUR)": "",
      "Notes": "",
      "ID": "",
      "Currency conversion fee (EUR)": "0.03",
      "Stamp duty reserve tax (EUR)": ""
    },
    {
      "Action": "Market sell",
      "Time": "2021-06-08 16:52:41",
      "ISIN": "US92532F1003",
      "Ticker": "VRTX",
      "Name": "\"Vertex Pharmaceuticals\"",
      "No. of shares": "0.1150000000",
      "Price / share": "210.30",
      "Currency (Price / share)": "USD",
      "Exchange rate": "1.21809",
      "Result (EUR)": "-1.71",
      "Total (EUR)": "19.82",
      "Charge amount (EUR)": "",
      "Notes": "",
      "ID": "",
      "Currency conversion fee (EUR)": "0.03",
      "Stamp duty reserve tax (EUR)": ""
    },
    {
      "Action": "Market sell",
      "Time": "2021-06-08 16:52:44",
      "ISIN": "US72352L1061",
      "Ticker": "PINS",
      "Name": "\"Pinterest\"",
      "No. of shares": "0.3500000000",
      "Price / share": "66.17",
      "Currency (Price / share)": "USD",
      "Exchange rate": "1.21818",
      "Result (EUR)": "-4.00",
      "Total (EUR)": "18.98",
      "Charge amount (EUR)": "",
      "Notes": "",
      "ID": "",
      "Currency conversion fee (EUR)": "0.03",
      "Stamp duty reserve tax (EUR)": ""
    },
    {
      "Action": "Market buy",
      "Time": "2021-06-08 16:53:26",
      "ISIN": "US95058W1009",
      "Ticker": "WEN",
      "Name": "\"The Wendy's\"",
      "No. of shares": "2.4000000000",
      "Price / share": "27.52",
      "Currency (Price / share)": "USD",
      "Exchange rate": "1.21779",
      "Result (EUR)": "",
      "Total (EUR)": "54.32",
      "Charge amount (EUR)": "",
      "Notes": "",
      "ID": "",
      "Currency conversion fee (EUR)": "0.08",
      "Stamp duty reserve tax (EUR)": ""
    },
    {
      "Action": "Market sell",
      "Time": "2021-06-08 16:53:27",
      "ISIN": "US5916971071",
      "Ticker": "MILE",
      "Name": "\"MetroMile\"",
      "No. of shares": "4.0000000000",
      "Price / share": "10.96",
      "Currency (Price / share)": "USD",
      "Exchange rate": "1.21804",
      "Result (EUR)": "-11.04",
      "Total (EUR)": "35.94",
      "Charge amount (EUR)": "",
      "Notes": "",
      "ID": "",
      "Currency conversion fee (EUR)": "0.05",
      "Stamp duty reserve tax (EUR)": ""
    },
    {
      "Action": "Market buy",
      "Time": "2021-06-08 16:53:48",
      "ISIN": "US95058W1009",
      "Ticker": "WEN",
      "Name": "\"The Wendy's\"",
      "No. of shares": "1.5500000000",
      "Price / share": "27.54",
      "Currency (Price / share)": "USD",
      "Exchange rate": "1.21788",
      "Result (EUR)": "",
      "Total (EUR)": "35.10",
      "Charge amount (EUR)": "",
      "Notes": "",
      "ID": "",
      "Currency conversion fee (EUR)": "0.05",
      "Stamp duty reserve tax (EUR)": ""
    },
    {
      "Action": "Market sell",
      "Time": "2021-07-06 13:30:04",
      "ISIN": "US95058W1009",
      "Ticker": "WEN",
      "Name": "\"The Wendy's\"",
      "No. of shares": "3.9500000000",
      "Price / share": "23.10",
      "Currency (Price / share)": "USD",
      "Exchange rate": "1.18325",
      "Result (EUR)": "-12.18",
      "Total (EUR)": "76.99",
      "Charge amount (EUR)": "",
      "Notes": "",
      "ID": "",
      "Currency conversion fee (EUR)": "0.12",
      "Stamp duty reserve tax (EUR)": ""
    },
    {
      "Action": "Market buy",
      "Time": "19/07/2021 13:30",
      "ISIN": "US88160R1014",
      "Ticker": "TSLA",
      "Name": "\"Tesla\"",
      "No. of shares": "0.1450000000",
      "Price / share": "629.79",
      "Currency (Price / share)": "USD",
      "Exchange rate": "1.18117",
      "Result (EUR)": "",
      "Total (EUR)": "77.43",
      "Charge amount (EUR)": "",
      "Notes": "",
      "ID": "",
      "Currency conversion fee (EUR)": "0.12",
      "Stamp duty reserve tax (EUR)": ""
    },
  ]

export default tradingHistory;